name: RW_APP
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - geopandas
  - movingpandas
  - pluggy
  - python-dotenv
  - deprecated
  - pip
  - pip:
      - -e ./random-walk-python
