name: test

on: [push]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Configure Git to rewrite SSH â†’ HTTPS for GitLab
        run: |
          git config --global url."https://${{ secrets.GITLAB_TOKEN }}@gitlab.tu-dortmund.de/".insteadOf "git@gitlab.tu-dortmund.de:"
          
      - name: Configure GitLab credentials
        run: |
          git config --global url."https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.tu-dortmund.de/".insteadOf "git@gitlab.tu-dortmund.de:"
          git config --global url."https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.tu-dortmund.de/".insteadOf "https://gitlab.tu-dortmund.de/"

      - name: Checkout repository including private submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Test via build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile_unittest
          push: false
